### ISSUE TITLE
Logging into ES

### ISSUE THREAD

**Issue by alen-z** [blacktop/docker-bro#8] opened 2017-12-01 20:50 UTC
Any idea why I'm not getting logs indexed in ES?

```docker
docker run -d --rm --name elasticsearch -p 80:80 -p 9200:9200 blacktop/elastic-stack:5.6
docker run -it --rm -v /my_path:/pcap --link elasticsearch blacktop/bro:elastic bro-watch
```

Files are available in `/pcap`. `bro -r test.pcap local` only creates `.state` directory. Kibana is accessible and index is created.

**Comment by blacktop** [comment] 2017-12-02 20:23
hmmm seems like something broke with the bro elasticsearch plugin?  I think they were going to deprecate it?  I have recreated what you are seeing and it no longer works for me either.

**Comment by blacktop** [comment] 2017-12-02 20:39
Let me know if that last commit helps please.

**Comment by blacktop** [comment] 2017-12-02 23:08
It still seems to not be working 😞

**Comment by alen-z** [comment] 2017-12-02 23:13
@blacktop, I appreciate you taking the time for looking into this.

No, it doesn't work. I even replaced `/tmp/bro/aux/plugins/elasticsearch` with the one you place at `/tmp/bro/aux/plugins/bro-plugins/elasticsearch`.

I'm interested in finding a solution and today's debugging suggests that bro's elasticsearch plugin could be the one that doesn't do the job. Documentation is poor and states it's "experimental". I tried with elastic-stack:4.6 and 5.x together with some [template.json](docker-bro/elastic/template.json) changes w/o any success.

```log
5.2
template.json string -> text w/ index removed

[2017-12-02T23:02:30,274][INFO ][o.e.n.Node               ] [] initializing ...
[2017-12-02T23:02:31,015][INFO ][o.e.e.NodeEnvironment    ] [hWEtvJa] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda2)]], net usable_space [46.9gb], net total_space [59gb], spins? [possibly], types [ext4]
[2017-12-02T23:02:31,016][INFO ][o.e.e.NodeEnvironment    ] [hWEtvJa] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-12-02T23:02:31,019][INFO ][o.e.n.Node               ] node name [hWEtvJa] derived from node ID [hWEtvJazTGObtomZkQzm4g]; set [node.name] to override
[2017-12-02T23:02:31,025][INFO ][o.e.n.Node               ] version[5.2.0], pid[24], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Linux/4.9.49-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [aggs-matrix-stats]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [ingest-common]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [lang-expression]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [lang-groovy]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [lang-mustache]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [lang-painless]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [percolator]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [reindex]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [transport-netty3]
[2017-12-02T23:02:33,115][INFO ][o.e.p.PluginsService     ] [hWEtvJa] loaded module [transport-netty4]
[2017-12-02T23:02:33,116][INFO ][o.e.p.PluginsService     ] [hWEtvJa] no plugins loaded
[2017-12-02T23:02:33,554][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
[2017-12-02T23:02:38,150][INFO ][o.e.n.Node               ] initialized
[2017-12-02T23:02:38,150][INFO ][o.e.n.Node               ] [hWEtvJa] starting ...
[2017-12-02T23:02:38,564][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 66:67:f9:49:fb:db:b3:24
[2017-12-02T23:02:38,756][INFO ][o.e.t.TransportService   ] [hWEtvJa] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2017-12-02T23:02:41,960][INFO ][o.e.c.s.ClusterService   ] [hWEtvJa] new_master {hWEtvJa}{hWEtvJazTGObtomZkQzm4g}{oH6nWo3bSM25Nc59HHsPOg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-12-02T23:02:42,008][INFO ][o.e.h.HttpServer         ] [hWEtvJa] publish_address {172.17.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2017-12-02T23:02:42,008][INFO ][o.e.n.Node               ] [hWEtvJa] started
[2017-12-02T23:02:42,078][INFO ][o.e.g.GatewayService     ] [hWEtvJa] recovered [0] indices into cluster_state
[2017-12-02T23:02:47,718][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [buildNum]
[2017-12-02T23:02:47,761][INFO ][o.e.c.m.MetaDataCreateIndexService] [hWEtvJa] [.kibana] creating index, cause [api], templates [], shards [1]/[1], mappings [server, config]
[2017-12-02T23:02:49,377][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [.kibana/dLlBT4LdT4iw1P9Mhxhbfw] create_mapping [index-pattern]
[2017-12-02T23:04:03,543][INFO ][o.e.c.m.MetaDataCreateIndexService] [hWEtvJa] [bro-201404102100] creating index, cause [auto(bulk api)], templates [bro], shards [5]/[1], mappings [weird, _default_, conn, dns, http, files, location, ssl, intel, notice]
[2017-12-02T23:04:03,780][INFO ][o.e.c.m.MetaDataCreateIndexService] [hWEtvJa] [@bro-meta] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2017-12-02T23:04:04,484][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [@bro-meta/F5JO4psoTfikvZwHGNiaHQ] create_mapping [index]
[2017-12-02T23:04:04,566][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] update_mapping [conn]
[2017-12-02T23:04:04,574][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] create_mapping [x509]
[2017-12-02T23:04:04,582][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] update_mapping [files]
[2017-12-02T23:04:04,689][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] create_mapping [stats]
[2017-12-02T23:04:04,694][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] create_mapping [capture_loss]
[2017-12-02T23:04:04,700][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] create_mapping [reporter]
[2017-12-02T23:04:04,857][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] update_mapping [notice]
[2017-12-02T23:04:04,880][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] update_mapping [notice]
[2017-12-02T23:04:05,008][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] update_mapping [ssl]
[2017-12-02T23:04:05,018][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [bro-201404102100/YQ1g0S9yTea2i21gdsJ_tw] create_mapping [loaded_scripts]
[2017-12-02T23:04:25,770][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [.kibana/dLlBT4LdT4iw1P9Mhxhbfw] update_mapping [config]
[2017-12-02T23:04:27,169][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [title]
[2017-12-02T23:04:27,170][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [description]
[2017-12-02T23:04:27,171][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [columns]
[2017-12-02T23:04:27,171][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [sort]
[2017-12-02T23:04:27,171][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [searchSourceJSON]
[2017-12-02T23:04:27,172][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [title]
[2017-12-02T23:04:27,173][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [description]
[2017-12-02T23:04:27,173][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [columns]
[2017-12-02T23:04:27,173][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [sort]
[2017-12-02T23:04:27,173][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [searchSourceJSON]
[2017-12-02T23:04:27,174][INFO ][o.e.c.m.MetaDataMappingService] [hWEtvJa] [.kibana/dLlBT4LdT4iw1P9Mhxhbfw] create_mapping [search]
```
There, fields like searchSourceJSON are coming somewhere from internal mapping? Kibana is still empty.

Generally, looking at `/var/log/elasticsearch.stdout.log` can give some clues.

One option is logstash parsing bro logs as suggested [here](https://medium.com/@utham/bro-elk-stack-integration-part-3-4fe02b5ff519) and few other places.

Suggestion for [docker-bro/docs/elastic.md](docker-bro/docs/elastic.md) update:
```docker
$ docker run -d --name elstack -p 80:80 -p 9200:9200 blacktop/elastic-stack:5.6
$ docker run -it --rm -v `pwd`:/pcap --link elstack:elasticsearch blacktop/bro:elastic bro-watch
```
It maps internal Docker host `elastichost` to `elstack`, which is expected to exist by [entrypoint.sh](docker-bro/elastic/entrypoint.sh). Or change `elstack` to `elasticsearch`. Otherwise it's not reachable from `blacktop/bro:elastic` image.

**Comment by blacktop** [comment] 2017-12-02 23:25
Ya I agree that this isn't a good solution, but it worked pretty well for a while :(

I had started work on another solution which I still think might be the best here - https://github.com/blacktop/brobeat

**Comment by alen-z** [comment] 2017-12-02 23:49
Don't have go on my mac and maybe some other dependencies:
```
$ make
go build
bash: go: command not found
make: *** [brobeat] Error 127
```
In elastic/Dockerfile:
```
(1/1) Installing go (1.8.4-r0)
Executing busybox-1.26.2-r9.trigger
OK: 718 MiB in 78 packages
 ---> 304d7708486f
Removing intermediate container 4de050c5517d
Step 12/26 : RUN cd /   && git clone https://github.com/blacktop/brobeat.git   && cd brobeat   && make
 ---> Running in 53d525de1841
Cloning into 'brobeat'...
make: bash: Command not found
make: bash: Command not found
make: bash: Command not found
make: bash: Command not found
make: bash: Command not found
go build
make: bash: Command not found
make: bash: Command not found
make: *** [vendor/github.com/elastic/beats/libbeat/scripts/Makefile:82: brobeat] Error 127
```

**Comment by blacktop** [comment] 2017-12-03 02:42
I think something broke with the new Bro 2.5.2? because none of the plugins are working anymore???

**Comment by alen-z** [comment] 2017-12-03 11:07
Hate to wait for bro to build from source to try those things :)

I guess it doesn't work for me.

**Comment by blacktop** [comment] 2017-12-03 15:27
Very true it is very annoying to have to wait for 20-30 mins every time I make a fix to see if it fixed anything.  I wish it was written in Golang 😉

**Comment by blacktop** [comment] 2017-12-03 16:18
DUDE!!!!!! IT WORKS!!!!!!

So I just rebuilt with the old 2.5.1 bro base and it works again.  My builds are super back logged in the Docker Cloud because I was making so much changes, but when it finally gets around to rebuilding the plugin tags `elastic` and `kafka` etc etc I think we are back in business!! 🎉

**Comment by alen-z** [comment] 2017-12-03 17:16
Haha, I can feel your enthusiasm :) Guess I'm doing something wrong.

1. I built elastic Dockerfile
2. Started elastic-stack:5.6
3. Started local image built from elastic Dockerfile linked to elastic-stack with bro-watch and still no data in Kibana after bro -r heartbleed.pcap local.

I would appreciate if you would share your workflow for getting results in Kibana.

Edit:
Oh cooomeee ooon! It was the filter which was set to last 15 minutes. :D

P.S. You were a great company to have over the weekend :) Happy holidays and keep broing!

**Comment by blacktop** [comment] 2017-12-03 19:56
Oh yeah I forgot to mention that test PCAP is pretty old now, which means the 15 min filter will miss it 👍 

Glad I could help, I am glad that the bro community has embraced my docker images and want to keep them working.  So thank YOU for pointing this out to me.  

I have SOOO many projects on Github now it is hard to do deep regression testing on them and make sure nothing Bro did breaks my images and plugins etc.

Can we close this issue now?

**Comment by alen-z** [comment] 2017-12-03 20:20
Please, feel free to do so.

**Comment by blacktop** [comment] 2017-12-03 20:22
Cheers!

**Closed as completed by blacktop** 2017-12-03 20:22 UTC
